import { StyleSheet } from "react-native";
import { width, height, colorPallete } from "../Onboarding/styles";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    width: width * 1,
  },
  subcontainer: {
    flex: 1,
    width: width * 0.9,
  },
  textAndImg: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: height * 0.1,
    width: width * 1,
    justifyContent: "space-between",
    paddingHorizontal: width * 0.03,
  },
  textAndImgMaps: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: height * 0.12,
    width: width * 1,
    justifyContent: "space-between",
    paddingHorizontal: width * 0.03,
  },
  inputs: {
    flex: 3,
    height: height * 0.35,
    width: width * 1,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingHorizontal: width * 0.01,
  },
  titleText: {
    fontFamily: "Gotham-Bold",
    fontSize: 24,
  },
  logoImage: {
    resizeMode: "contain",
    height: height * 0.2,
    width: width * 0.22,
  },
  body: {
    flex: 4,
    width: "100%",
    marginLeft: 15,
  },
  input: {
    fontFamily: "Gotham-Book",
    backgroundColor: "#fff",
    borderRadius: 5,
    fontSize: 15,
  },
  label: {
    fontFamily: "Gotham-Medium",
    fontSize: 18,
    color: colorPallete.second,
    fontWeight: "normal",
  },
  inputError: {
    backgroundColor: "#d7eae9",
    borderColor: "red",
    borderRadius: 14,
    paddingLeft: 12,
    marginBottom: 5,
    borderWidth: 2,
    marginTop: 1,
    alignItems: "center",
  },
  btnExit: {
    flexDirection: "row",
    backgroundColor: colorPallete.first,
    height: height * 0.08,
    width: width * 0.4,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    marginBottom: 20,
  },
  btnContinue: {
    flexDirection: "row",
    backgroundColor: colorPallete.third,
    height: height * 0.08,
    width: width * 0.4,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    marginBottom: 20,
  },
  btnCancelarPrewiew: {
    backgroundColor: "#00BD9D",
    height: 50,
    width: 120,
    // paddingLeft: 5,
    paddingHorizontal: 4,
    paddingBottom: 10,
    // paddingRight: 5,
    paddingTop: 10,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 15,
    // borderWidth: 1,
    // borderColor: 'black'
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  categoriesView: {
    flex: 1,
    flexDirection: "row",
  },
  btnCategories: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    backgroundColor: "#fff",
    height: 36,
    width: 134,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 5,
    marginLeft: 10,
    marginBottom: 15,
    borderWidth: 1.5,
    borderColor: "#d7eae9",
  },
  catIcon: {
    marginRight: 8,
    marginTop: 2,
    marginLeft: 6,
  },
  textCat: {
    alignSelf: "flex-start",
    paddingLeft: 12,
    paddingTop: 5,
    fontSize: 16,
  },
  btnsContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginTop: height * 0.025,
    width: width * 1,
    paddingHorizontal: width * 0.025,
  },
  btnsContainerMaps: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    //marginTop: "10%",
    marginBottom: "10%",
  },
  textBtn: {
    fontFamily: "Gotham-Medium",
    color: "white",
    textAlign: "center",
    fontWeight: "normal",
    fontSize: 20,
  },
  btnContainer: {
    paddingRight: 25,
    paddingLeft: 25,
  },
  textType: {
    fontFamily: "Gotham-Medium",
    color: colorPallete.second,
    fontSize: 18,
  },
  checkBox: {
    flexDirection: "row",
    width: width * 0.95,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  boxCont: {
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  categoryContainer: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: width * 0.03,
  },
  text: {
    marginBottom: 10,
  },
  textContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  icn: {
    // position:'absolute',
    alignItems: "flex-start",
    // marginLeft:8,
    // marginTop:326,
    // marginTop:12
  },
  lefticn: {
    // marginLeft:1
    // position:'absolute',
    alignItems: "center",
  },
  calendarContainer: {
    // flexDirection: 'row',
    // marginBottom: 35,
    // marginTop: 5,
    marginHorizontal: 6,
  },
  calendar: {
    marginLeft: 10,
    // marginTop:2
  },
  inputHoraContainer: {
    // borderBottomWidth: 0,
    marginRight: 40,
  },
  reloj: {
    marginRight: 40,
    marginBottom: 8,

    // marginBottom:100,
    // position:'absolute'
  },
  dateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: width * 1,
    paddingHorizontal: width * 0.01,
  },
  horaCont: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginLeft: 8,
  },
  btn2: {
    elevation: 3,
    height: height * 0.06,
    width: width * 0.4,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: height * 0.03,
    backgroundColor: colorPallete.fourth,
    borderRadius: 7,
  },
  containerMap: {
    shadowColor: "#000",
    shadowOffset: {
      width: 2,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 4,
  },
  textMaps: {
    fontFamily: "Gotham-Medium",
    fontSize: 16,
    color: "white",
  },
  textLoc: {
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: -20,
  },
  photosContainer: {
    flex: 3,
    paddingHorizontal: width * 0.03,
    width: width * 1,
  },
  photosText: {
    marginBottom: 5,
    fontFamily: "Gotham-Medium",
    fontSize: 18,
    color: colorPallete.second,
  },
  photoBtn: {
    elevation: 3,
    backgroundColor: colorPallete.fourth,
    borderRadius: 5,
    width: width * 0.65,
    height: height * 0.05,
    justifyContent: "center",
    marginVertical: 10,
  },
  textPhotoBtn: {
    fontSize: 14,
    fontFamily: "Gotham-Medium",
    color: "white",
    textAlign: "center",
  },
  selectedPhotosText: {
    fontFamily: "Gotham-Book",
    fontSize: 15,
    marginBottom: 6,
  },
  typeEvent: {
    flex: 1,
    paddingHorizontal: width * 0.03,
    marginVertical: height * 0.01,
  },
  pickerContainer: {
    backgroundColor: "#fff",
    marginVertical: height * 0.01,
    alignItems: "center",
    width: width * 0.35,
    height: height * 0.05,
    justifyContent: "center",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colorPallete.second,
    elevation: 3,
  },
  picker: {
    alignSelf: "center",
    width: "100%",
    color: "black",
  },
  cancelBtn: {
    backgroundColor: "#eee",
    height: 50,
    width: 120,
    paddingHorizontal: 4,
    paddingBottom: 10,
    paddingTop: 10,
    borderRadius: 6,
    marginLeft: 8,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 15,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  btnAceptar: {
    backgroundColor: "#00BD9D",
    height: 50,
    width: 160,
    paddingHorizontal: 4,
    paddingBottom: 10,
    paddingTop: 10,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 15,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  btnAceptarPrewiew: {
    backgroundColor: "#00BD9D",
    height: 50,
    width: 120,
    paddingHorizontal: 4,
    paddingBottom: 10,
    paddingTop: 10,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 15,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cancelTextBtn: {
    color: "black",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 20,
  },
  btnsContaineratras: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 200,
  },
  header: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: colorPallete.fifth,
    height: height * 0.07,
  },
  headerMap: {
    justifyContent: "center",
    alignItems: "center",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: colorPallete.fifth,
    height: height * 0.07,
  },
  textHeader: {
    fontFamily: "Gotham-Medium",
    color: colorPallete.third,
    fontSize: 20,
    textDecorationLine: "underline",
  },
  btnX: {
    height: height * 0.2,
    marginVertical: height * 0.015,
    borderRadius: 10,
    marginHorizontal: 3,
  },
  pickedImg: {
    width: width * 0.455,
    height: height * 0.2,
    borderRadius: 10,
  },
});

export default styles;
